/**
 * BulkUpdateResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Record} from "./Record";

export interface BulkUpdateResponse {
    createdRecords?: Array<string>
    updatedRecords?: Array<string>
    records?: Array<Record>
}

