/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import axios, {AxiosRequestConfig} from "axios";
import {ClientAbstract, CredentialsInterface, TokenStoreInterface} from "sdkgen-client"
import {HttpBearer} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {MetaTag} from "./MetaTag";
import {RecordsTag} from "./RecordsTag";
import {FieldsTag} from "./FieldsTag";

export class Client extends ClientAbstract {
    public meta(): MetaTag
    {
        return new MetaTag(
            this.httpClient,
            this.parser
        );
    }

    public records(): RecordsTag
    {
        return new RecordsTag(
            this.httpClient,
            this.parser
        );
    }

    public fields(): FieldsTag
    {
        return new FieldsTag(
            this.httpClient,
            this.parser
        );
    }



    public static build(token: string): Client
    {
        return new Client('https://api.airtable.com/', new HttpBearer(token));
    }
}
