/**
 * CommentReaction automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommentAuthor} from "./CommentAuthor";

export interface CommentReaction {
    emoji?: string
    reactingUser?: CommentAuthor
}

