/**
 * CommentCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Comment} from "./Comment";

export interface CommentCollection {
    offset?: string
    records?: Array<Comment>
}

