/**
 * CommentAuthor automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface CommentAuthor {
    id?: string
    email?: string
    name?: string
}
