/**
 * Comment automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommentAuthor} from "./CommentAuthor";

export interface Comment {
    id?: string
    createdTime?: string
    lastUpdatedTime?: string
    text?: string
    parentCommentId?: string
    reactions?: string
    author?: CommentAuthor
}

