/**
 * DeleteResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface DeleteResponse {
    deleted?: boolean
    id?: string
}
