/**
 * Error automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ErrorDetails} from "./ErrorDetails";
export interface Error {
    error?: ErrorDetails
}
