/**
 * Field automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {FieldOptions} from "./FieldOptions";
export interface Field {
    id?: string
    type?: string
    name?: string
    description?: string
    options?: FieldOptions
}
