/**
 * MetaTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {Error} from "./Error";
import {ErrorException} from "./ErrorException";
import {User} from "./User";

export class MetaTag extends TagAbstract {
    /**
     * Retrieve the user's ID. For OAuth access tokens, the scopes associated with the token used are also returned.
     *
     * @returns {Promise<User>}
     * @throws {ErrorException}
     * @throws {ClientException}
     */
    public async getWhoami(): Promise<User> {
        const url = this.parser.url('/v0/meta/whoami', {
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as User;
        }

        const statusCode = response.status;
        if (statusCode >= 0 && statusCode <= 999) {
            throw new ErrorException(await response.json() as Error);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
