/**
 * Record automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface Record {
    id?: string
    createdTime?: string
    fields?: globalThis.Record<string, any>
}
