/**
 * RecordCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Record} from "./Record";

export interface RecordCollection {
    offset?: string
    records?: Array<Record>
}

