/**
 * Table automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Field} from "./Field";

export interface Table {
    id?: string
    primaryFieldId?: string
    name?: string
    description?: string
    fields?: Array<Field>
}

